export enum ErrorCode {
  
  VALIDATION_ERROR = "VALIDATION_ERROR",

  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",


  JWT_TOKEN_EXPIRED = "JWT_TOKEN_EXPIRED",
  JWT_ERROR = "JWT_ERROR",
  
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",

  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",


   // Company Error Codes
  COMPANY_NOT_FOUND= "COMPANY_NOT_FOUND",
  COMPANY_ALREADY_EXISTS= "COMPANY_ALREADY_EXISTS",
  NOT_COMPANY_MEMBER= "NOT_COMPANY_MEMBER",
  COMPANY_DELETED= "COMPANY_DELETED",
  NOT_AUTHORIZED_FOR_COMPANY= "NOT_AUTHORIZED_FOR_COMPANY",
  INVALID_COMPANY_DATA= "INVALID_COMPANY_DATA",

  CONFLICT = "CONFLICT",
   FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL_ERROR = "INTERNAL_ERROR"
}